name: Deploy App (Blue/Green)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to set up Azure environment
  setup-azure-env:
    env:
      RESOURCE_GROUP_NAME: vmss303-resources
      RELEASE_FOLDER_NAME: 1.234
      BLOB_CONTAINER_NAME: appcontainer
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
          enable-AzPSSession: true
  
      - name: Azure PowerShell App Deploy Action 
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript:
            ./automation/Deploy-Application.ps1 -ResourceGroupName ${{ env.RESOURCE_GROUP_NAME }} -BlobContainerName ${{ env.BLOB_CONTAINER_NAME }} -ReleaseFolderName ${{ env.RELEASE_FOLDER_NAME }}
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest

      